### ISSUE TITLE
[nri-statsd] Review the docs for values that could have changed

### ISSUE THREAD

**Issue by kang-makes** [newrelic/newrelic-coreint#301] opened 2022-02-25 12:39 UTC
- [ ] Take a look how was README.md automated in newrelic-k8s-metrics-adapter: newrelic/newrelic-k8s-metrics-adapter#39
- [ ] Review that the values.yaml is properly documented to enable the creation of the README.md file automatically.
- [ ] Review docs.newrelic.com for any `values.yaml` that should be changed in the integrations/kubernetes integration.

Note: this issue was created here instead of inside `newrelic/nri-statsd` because we are not owners of that repository and we could not see it in our ZenHub Sprint board.

**Comment by davidgit** [comment] 2022-04-08 13:45
Duplicate of https://github.com/newrelic/nri-statsd/issues/25

**Closed by davidgit** 2022-04-08 13:45 UTC
