### ISSUE TITLE
[nri-statsd] Copy the template chart to the repository and make the pipelines work with it

### ISSUE THREAD

**Issue by kang-makes** [newrelic/newrelic-coreint#299] opened 2022-02-25 10:31 UTC
- [ ] Modify the pipeline to release this chart. Use `k8s-metrics-adapter` as an example: newrelic/newrelic-k8s-metrics-adapter#37
- [ ] To test the deployment of the chart, copy the template with the [helm chart's repository common library folder](https://github.com/newrelic/helm-charts/tree/feature/common-library/library/CHART-TEMPLATE)

Note: this issue was created here instead of inside `newrelic/nri-statsd` because we are not owners of that repository and we could not see it in our ZenHub Sprint board.

**Comment by davidgit** [comment] 2022-04-08 13:43
Duplicate of https://github.com/newrelic/nri-statsd/issues/26

**Closed by davidgit** 2022-04-08 13:43 UTC
