### ISSUE TITLE
[nri-statsd] Adapt the template chart copied to the integration’s needs

### ISSUE THREAD

**Issue by kang-makes** [newrelic/newrelic-coreint#300] opened 2022-02-25 12:27 UTC
In #299 we created and tested a pipeline that was able to deploy helm charts in this repository.

Now we have to adapt that helm chart to have all the features that it has the original [helm-repository](https://github.com/newrelic/helm-charts/tree/master/charts/nri-statsd)

Please, take also care of any possible issue that could be open on the [helm-chart repository](https://github.com/newrelic/helm-charts/issues/). I had triaged them but some of them could have slipped to it.

You should take at least a glance at this issue/s:
 - newrelic/helm-charts#373 

Note: this issue was created here instead of inside newrelic/nri-statsd because we are not owners of that repository and we could not see it in our ZenHub Sprint board.

**Comment by davidgit** [comment] 2022-04-08 13:44
Duplicate of https://github.com/newrelic/nri-statsd/issues/24

**Closed by davidgit** 2022-04-08 13:44 UTC
